import { TelemetryInput, evaluateTelemetry } from "./engine";

export interface ScenarioDefinition {
  id: string;
  key: "A" | "B" | "C" | "D" | "E" | "F";
  title: string;
  category: "ATTACK" | "BENIGN";
  threatActor?: string;
  summary: string;
  expectedOutcome: string;
  telemetryStream: TelemetryInput[];
  mitreTechniques: { id: string; name: string; tactic: string }[];
  affectedAssets: string[];
  recommendedAction: string;
  cvssBaseScore: number;
}

export const SCENARIOS: Record<string, ScenarioDefinition> = {
  A: {
    id: "scenario-a",
    key: "A",
    title: "APT29 Lateral Movement & DC Takeover",
    category: "ATTACK",
    threatActor: "Cozy Bear (APT29)",
    summary: "Suspicious Kerberos ticket request followed by pass-the-hash authentication across internal subnets targeting the primary Domain Controller.",
    expectedOutcome: "Autonomous Subnet Isolation and Kerberos Service Account Ticket Revocation triggered (Confidence >= 0.82).",
    affectedAssets: ["WS-EXEC-01", "SRV-APPS-02", "DC-CORP-PRIMARY"],
    recommendedAction: "ISOLATE_HOST",
    cvssBaseScore: 8.8,
    mitreTechniques: [
      { id: "T1078", name: "Valid Accounts", tactic: "Initial Access" },
      { id: "T1550", name: "Use Alternate Authentication Material", tactic: "Defense Evasion" },
      { id: "T1021", name: "Remote Services: SMB/Windows Admin Shares", tactic: "Lateral Movement" },
      { id: "T1003", name: "OS Credential Dumping: LSASS Memory", tactic: "Credential Access" },
    ],
    telemetryStream: [
      {
        entityId: "WS-EXEC-01",
        sourceType: "AUTH",
        sourceIp: "192.168.10.45",
        destIp: "10.0.0.10",
        action: "kerberos_unusual_tgt_request",
        username: "svc_deploy",
        hostname: "WS-EXEC-01",
        assetCriticality: "HIGH",
        isOffHours: true,
        bytesOut: 4200,
        sequenceContext: ["initial_access"],
      },
      {
        entityId: "DC-CORP-PRIMARY",
        sourceType: "SYSTEM",
        sourceIp: "192.168.10.45",
        destIp: "10.0.0.5",
        action: "mimikatz_lsass_injection",
        processName: "powershell.exe -enc JABj...",
        username: "SYSTEM",
        hostname: "DC-CORP-PRIMARY",
        assetCriticality: "CRITICAL",
        isOffHours: true,
        bytesOut: 18500,
        sequenceContext: ["initial_access", "privilege_escalation"],
      },
    ],
  },

  B: {
    id: "scenario-b",
    key: "B",
    title: "Distributed Credential Stuffing & Impossible Travel",
    category: "ATTACK",
    threatActor: "Botnet Cluster (Mirai Variant)",
    summary: "Over 200 failed login attempts within 60 seconds followed by a successful SSO login from Dallas, TX just 4 minutes after an authenticated session in Tokyo, Japan.",
    expectedOutcome: "Immediate IP Blocking of ingress subnets and mandatory user session revocation with MFA step-up challenge.",
    affectedAssets: ["GW-AUTH-EXTERNAL", "IAM-OKTA-GATEWAY"],
    recommendedAction: "BLOCK_IP",
    cvssBaseScore: 7.5,
    mitreTechniques: [
      { id: "T1110", name: "Brute Force: Credential Stuffing", tactic: "Credential Access" },
      { id: "T1078", name: "Valid Accounts: Cloud Accounts", tactic: "Defense Evasion" },
      { id: "T1556", name: "Modify Authentication Process", tactic: "Persistence" },
    ],
    telemetryStream: [
      {
        entityId: "GW-AUTH-EXTERNAL",
        sourceType: "AUTH",
        sourceIp: "185.220.101.5",
        destIp: "10.0.1.1",
        action: "credential_stuffing_burst",
        username: "admin@aegis.corp",
        hostname: "GW-AUTH-EXTERNAL",
        assetCriticality: "HIGH",
        isOffHours: false,
        bytesOut: 9800,
        payloadSnippet: "POST /api/v1/auth/login HTTP/1.1 User-Agent: Mozilla/5.0 (Windows NT 10.0)",
        sequenceContext: ["brute_force"],
      },
      {
        entityId: "IAM-OKTA-GATEWAY",
        sourceType: "AUTH",
        sourceIp: "45.154.255.89",
        destIp: "10.0.1.5",
        action: "impossible_travel_login_success",
        username: "ciso@aegis.corp",
        hostname: "IAM-OKTA-GATEWAY",
        assetCriticality: "CRITICAL",
        isOffHours: true,
        bytesOut: 3200,
        payloadSnippet: "Origin: Dallas, US (Prior session: Tokyo, JP 4m ago)",
        sequenceContext: ["initial_access"],
      },
    ],
  },

  C: {
    id: "scenario-c",
    key: "C",
    title: "Ransomware Outbreak & Shadow Copy Deletion",
    category: "ATTACK",
    threatActor: "BlackCat / ALPHV Syndicate",
    summary: "Execution of vssadmin to purge volume shadow copies, rapid encryption of sensitive shares, and outbound command-and-control communication.",
    expectedOutcome: "Autonomous Endpoint Quarantine and Network Disconnect of infected file server in under 150 milliseconds.",
    affectedAssets: ["FS-STORAGE-04", "DB-PAYMENTS-01"],
    recommendedAction: "ISOLATE_HOST",
    cvssBaseScore: 9.6,
    mitreTechniques: [
      { id: "T1490", name: "Inhibit System Recovery", tactic: "Impact" },
      { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
      { id: "T1059", name: "Command and Scripting Interpreter", tactic: "Execution" },
      { id: "T1071", name: "Application Layer Protocol: C2", tactic: "Command and Control" },
    ],
    telemetryStream: [
      {
        entityId: "FS-STORAGE-04",
        sourceType: "SYSTEM",
        sourceIp: "10.0.4.12",
        destIp: "10.0.4.1",
        action: "shadow_delete_vssadmin",
        processName: "vssadmin.exe delete shadows /all /quiet",
        username: "NT AUTHORITY\\SYSTEM",
        hostname: "FS-STORAGE-04",
        assetCriticality: "CRITICAL",
        isOffHours: true,
        bytesOut: 24000,
        payloadSnippet: "wmic shadowcopy delete /nointeractive & bcdedit /set {default} bootstatuspolicy ignoreallfailures",
        sequenceContext: ["execution", "impact"],
      },
      {
        entityId: "FS-STORAGE-04",
        sourceType: "NETWORK",
        sourceIp: "10.0.4.12",
        destIp: "91.240.118.172",
        port: 4444,
        protocol: "TCP",
        action: "c2_ip_outbound_beacon",
        hostname: "FS-STORAGE-04",
        assetCriticality: "CRITICAL",
        isOffHours: true,
        bytesOut: 48000,
        payloadSnippet: "ENCRYPTED_HEADER_BLKCAT_AES256",
        sequenceContext: ["impact", "c2"],
      },
    ],
  },

  D: {
    id: "scenario-d",
    key: "D",
    title: "DNS Tunneling & Covert Data Exfiltration",
    category: "ATTACK",
    threatActor: "OilRig (APT34)",
    summary: "Abnormal volume of high-entropy DNS TXT queries carrying encoded database records to an external rogue nameserver.",
    expectedOutcome: "Autonomous Egress Port Blocking and DNS Sinkholing of adversary domain with 0.83 confidence.",
    affectedAssets: ["DB-CUSTOMER-RECORDS", "DNS-RESOLVER-INTERNAL"],
    recommendedAction: "FIREWALL_DROP",
    cvssBaseScore: 8.2,
    mitreTechniques: [
      { id: "T1071.004", name: "Application Layer Protocol: DNS", tactic: "Command and Control" },
      { id: "T1048", name: "Exfiltration Over Alternative Protocol", tactic: "Exfiltration" },
      { id: "T1027", name: "Obfuscated Files or Information", tactic: "Defense Evasion" },
    ],
    telemetryStream: [
      {
        entityId: "DB-CUSTOMER-RECORDS",
        sourceType: "NETWORK",
        sourceIp: "10.0.2.88",
        destIp: "10.0.0.2",
        port: 53,
        protocol: "UDP",
        action: "dns_tunnel_exfiltration_burst",
        hostname: "DB-CUSTOMER-RECORDS",
        dnsQuery: "7b22757365725f73736e223a223034322d39382d31313437227d.exfil.darkops.io",
        payloadSnippet: "4d61737369766520456e74726f707920446174612053747265616d2038313932",
        assetCriticality: "HIGH",
        isOffHours: true,
        bytesOut: 38500,
        sequenceContext: ["exfiltration"],
      },
    ],
  },

  E: {
    id: "scenario-e",
    key: "E",
    title: "Cloud IAM Privilege Escalation & S3 Data Dumping",
    category: "ATTACK",
    threatActor: "Scattered Spider (UNC3944)",
    summary: "Compromised AWS IAM Access Key utilized to create an inline administrative policy, attach it to a newly spawned instance, and begin syncing production S3 buckets.",
    expectedOutcome: "Instant Revocation of IAM Access Key credentials and isolation of the rogue EC2 compute instance.",
    affectedAssets: ["AWS-PROD-VPC", "S3-FINANCIAL-ARCHIVE"],
    recommendedAction: "REVOKE_TOKEN",
    cvssBaseScore: 8.5,
    mitreTechniques: [
      { id: "T1098", name: "Account Manipulation", tactic: "Persistence" },
      { id: "T1068", name: "Exploitation for Privilege Escalation", tactic: "Privilege Escalation" },
      { id: "T1530", name: "Data from Cloud Storage Object", tactic: "Collection" },
    ],
    telemetryStream: [
      {
        entityId: "AWS-PROD-VPC",
        sourceType: "ALERT",
        sourceIp: "194.26.29.112",
        destIp: "172.31.0.1",
        action: "iam_attach_admin_policy",
        username: "dev_contractor_key",
        hostname: "AWS-PROD-VPC",
        assetCriticality: "HIGH",
        isOffHours: true,
        bytesOut: 12000,
        payloadSnippet: "Action: iam:PutUserPolicy PolicyName: FullAdminBypass Resource: *",
        sequenceContext: ["privilege_escalation"],
      },
      {
        entityId: "S3-FINANCIAL-ARCHIVE",
        sourceType: "NETWORK",
        sourceIp: "172.31.14.90",
        destIp: "52.216.0.0",
        action: "s3_bulk_sync_exfiltration",
        hostname: "S3-FINANCIAL-ARCHIVE",
        assetCriticality: "CRITICAL",
        isOffHours: true,
        bytesOut: 62000,
        sequenceContext: ["collection", "exfiltration"],
      },
    ],
  },

  F: {
    id: "scenario-f",
    key: "F",
    title: "Scheduled High-Volume Enterprise Backup (Benign Benchmark)",
    category: "BENIGN",
    threatActor: "Authorized Automation: Veeam Backup Agent",
    summary: "Nightly multi-gigabyte differential database backup transferred from main transactional database to offsite storage appliance.",
    expectedOutcome: "Correctly classified as BENIGN (Confidence < 0.25). Zero defensive action triggered, verified False-Positive suppression.",
    affectedAssets: ["DB-PAYMENTS-01", "BACKUP-STORAGE-APPLIANCE"],
    recommendedAction: "LOG_AND_MONITOR",
    cvssBaseScore: 0.0,
    mitreTechniques: [],
    telemetryStream: [
      {
        entityId: "DB-PAYMENTS-01",
        sourceType: "NETWORK",
        sourceIp: "10.0.3.15",
        destIp: "10.0.100.50",
        port: 445,
        protocol: "TCP",
        action: "scheduled_backup_transfer",
        processName: "veeam_agent.exe",
        username: "svc_backup_agent",
        hostname: "DB-PAYMENTS-01",
        assetCriticality: "CRITICAL",
        isOffHours: true,
        isServiceAccountOrScheduled: true,
        isHistoricalProfileMatch: true,
        bytesOut: 85000,
        payloadSnippet: "Veeam Encrypted Image Chunk Archive - Block ID: #8892110",
      },
    ],
  },
};
